### ISSUE TITLE
PHP version constraint

### ISSUE THREAD

**Issue by dizzystuff** [silverstripe-australia/silverstripe-queuedjobs#359] opened 2021-10-13 03:04 UTC
Can PHP 8 be added to the composer PHP version constraint? i.e. `"php": "^7.1 || ^8.0"`

**Comment by emteknetnz** [comment] 2021-10-17 20:51
Closing as this is a duplicate of https://github.com/symbiote/silverstripe-queuedjobs/issues/358

**Closed as completed by emteknetnz** 2021-10-17 20:51 UTC
