### ISSUE TITLE
Broken jobs won’t resume

### ISSUE THREAD

**Issue by lozcalver** [silverstripe-australia/silverstripe-queuedjobs#339] opened 2021-03-05 09:12 UTC
When a job (more than 1 “step”, not sure if that’s relevant) throws an exception, it’s marked with a JobStatus of `Broken`. The admin UI shows a button to resume the job:

<img width="202" alt="Screenshot 2021-03-05 at 09 06 30" src="https://user-images.githubusercontent.com/1655548/110092982-1ff85e00-7d92-11eb-88e5-6f412632d7ef.png">

Clicking this changes the JobStatus back to `Waiting`, but the job never tries to run again. The only way I can get it to run is by clicking to edit the job and deleting the hash(?) in the “Worker” field.

**Comment by maxime-rainville** [comment] 2021-03-08 02:32
I'm not sure what the expected behaviour is here. Is the problem that we're showing a "restart job" button that should be hidden ... or is restarting a broken job an supported interaction?

**Comment by lozcalver** [comment] 2021-03-08 09:08
Restarting broken jobs always used to be a supported interaction, I think the action just needs to be updated to clear the worker hash

**Comment by andrewandante** [comment] 2021-08-18 02:17
Yep I've seen this as well - the problem is that we can no longer grab the mutex as it's checking for the JobID with a null Worker. I think we need to disassociate the Worker when marking it as broken.

**Closed as completed** 2021-10-18 23:08 UTC
Labels: affects/v4, complexity/medium, impact/medium, type/bug

**Comment by maxime-rainville** [comment] 2021-10-19 08:21
I cherry-picked the fix into the 4.8 branch and tagged [4.8.1](https://github.com/symbiote/silverstripe-queuedjobs/releases/tag/4.8.1) to ship it.
